name: Eleventy Action
uses: TartanLlama/actions-eleventy@v1.2
  with:
    # Arguments to pass to the Eleventy invocation
    args: # optional
    # If set to `true`, `npm install` will be run before Eleventy is invoked
    install_dependencies: # optional
